# Generated by Django 5.2.17 on 2026-08-31 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepairTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                ("description", models.TextField(blank=True, verbose_name="Beskrivelse")),
                ("location", models.CharField(blank=True, max_length=200, verbose_name="Sted")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ny", "Ny"),
                            ("i_gang", "I gang"),
                            ("afventer", "Afventer"),
                            ("faerdig", "Færdig"),
                        ],
                        default="ny",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_repairs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
