# Generated by Django 5.2.17 on 2026-09-15 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import photo_album.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("folder", models.CharField(max_length=10, verbose_name="Mappe")),
                ("name", models.CharField(max_length=140, verbose_name="Albumnavn")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("manually_locked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-folder", "name"],
                "constraints": [
                    models.UniqueConstraint(fields=("folder", "name"), name="uniq_album_folder_name")
                ],
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("original", models.FileField(upload_to=photo_album.models.album_original_path)),
                (
                    "high_definition",
                    models.FileField(upload_to=photo_album.models.album_high_definition_path),
                ),
                ("thumbnail", models.FileField(upload_to=photo_album.models.album_thumbnail_path)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Afventer godkendelse"),
                            ("approved", "Godkendt"),
                            ("rejected", "Afvist"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="photo_album.album",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_deletions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["added_at", "pk"],
            },
        ),
    ]
