# Generated by Django 5.2.17 on 2026-09-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_album", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="unlocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
