# Generated by Django 5.2.17 on 2026-09-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_album", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="derivative_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="media",
            name="derivative_state",
            field=models.CharField(
                choices=[("ready", "Klar"), ("pending", "Behandles"), ("failed", "Mislykkedes")],
                default="ready",
                max_length=10,
            ),
        ),
    ]
