# Generated by Django 5.2.17 on 2026-09-15 21:34

from django.db import migrations, models

import photo_album.models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_album", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="high_definition",
            field=models.FileField(upload_to=photo_album.models.album_high_definition_path),
        ),
        migrations.AlterField(
            model_name="media",
            name="original",
            field=models.FileField(upload_to=photo_album.models.album_original_path),
        ),
        migrations.AlterField(
            model_name="media",
            name="thumbnail",
            field=models.FileField(upload_to=photo_album.models.album_thumbnail_path),
        ),
    ]
