# Generated by Django 5.2.17 on 2026-09-16 18:57

from django.db import migrations, models

import photo_album.models
import photo_album.storage


class Migration(migrations.Migration):
    dependencies = [
        ("photo_album", "0002_media_derivative_attempts_media_derivative_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="high_definition",
            field=models.FileField(
                storage=photo_album.storage.get_photo_album_storage,
                upload_to=photo_album.models.album_high_definition_path,
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="original",
            field=models.FileField(
                storage=photo_album.storage.get_photo_album_storage,
                upload_to=photo_album.models.album_original_path,
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="thumbnail",
            field=models.FileField(
                storage=photo_album.storage.get_photo_album_storage,
                upload_to=photo_album.models.album_thumbnail_path,
            ),
        ),
    ]
