# Generated by Django 5.2.17 on 2026-09-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_album", "0002_alter_media_high_definition_alter_media_original_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="captured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
