# Generated by Django 5.2.17 on 2026-09-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_album", "0003_media_captured_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="manually_locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
