# Generated by Django 5.2.17 on 2026-09-17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_album", "0003_alter_media_high_definition_alter_media_original_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("media_ids", models.JSONField(default=list)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("task_id", models.CharField(blank=True, max_length=36)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "I kø"),
                            ("building", "Bygges"),
                            ("ready", "Klar"),
                            ("failed", "Mislykkedes"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("archive_key", models.CharField(blank=True, max_length=255)),
                ("error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="photo_album.album",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-pk"]},
        ),
    ]
