# Generated by Django 5.2.17 on 2026-09-18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import photo_album.models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_album", "0004_albumdownload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("folder", models.CharField(max_length=10)),
                ("archive_name", models.CharField(max_length=255)),
                (
                    "archive",
                    models.FileField(
                        storage=photo_album.models.get_photo_album_storage,
                        upload_to=photo_album.models.album_import_path,
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("task_id", models.CharField(blank=True, max_length=36)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "I kø"),
                            ("building", "Importerer"),
                            ("ready", "Klar"),
                            ("failed", "Mislykkedes"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("album_ids", models.JSONField(default=list)),
                ("skipped", models.JSONField(default=list)),
                ("error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-pk"]},
        ),
    ]
