# Generated by Django 5.2.17 on 2026-09-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_album", "0005_albumimport"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="derivative_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
