<?php
# Originally generated by the MediaWiki 1.22.2 installer; carried forward to 1.35.
#
# 2026-08-04 — adapted for the Hetzner/Coolify deployment. Changes from the legacy file:
#   * database host/name/user/password, $wgSecretKey and $wgUpgradeKey now come from the
#     environment. The legacy file had all of them hardcoded, including the shared `gahk_dk`
#     password that App A, App B and MediaWiki all used.
#   * $wgDBTableOptions switched MyISAM -> InnoDB: the database was converted before the Aug 4 dump,
#     so the imported tables are InnoDB and update.php must not create new ones as MyISAM.
#   * $wgServer moved to the canonical host.
#   * $wgScriptExtension dropped — removed from MediaWiki in 1.26, ignored since.
# Everything else is unchanged from the legacy configuration.

# Protect against web entry
if (!defined('MEDIAWIKI')) {
    exit;
}

/**
 * Fail loudly at startup on a missing secret rather than silently running with an empty one.
 */
function gahkEnv($name, $default = null)
{
    $value = getenv($name);
    if ($value === false || $value === '') {
        if ($default !== null) {
            return $default;
        }
        die("Configuration error: environment variable $name is not set.\n");
    }
    // Reject un-substituted placeholders like "<openssl rand -hex 32>" or "<from step 2>". A quoted
    // heredoc copies these in verbatim, and a non-empty value otherwise sails straight through —
    // which for $wgSecretKey means a predictable key silently weakening CSRF and session security.
    if ($value[0] === '<' && substr($value, -1) === '>') {
        die("Configuration error: $name still holds the placeholder '$value'.\n");
    }
    return $value;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Gahk Wiki";
$wgMetaNamespace = "Gahk_Wiki";

$wgScriptPath = "/wiki";

# Coolify/Traefik routes gahk.dk/wiki here with a `stripprefix` middleware, so Apache receives
# "/index.php/Forside" while $wgScript is still "/wiki/index.php". MediaWiki extracts the page title
# by matching REQUEST_URI against the pattern "$wgScript/$1" (WebRequest::getPathInfo, via
# PathRouter). After the strip that match fails, so *every* path-style URL resolves to no title at
# all and renders the main page — which on a private wiki is "Log på nødvendigt" for every link,
# including the login link. The symptom is a login button that appears to do nothing: it navigates
# to a page identical to the one you left.
#
# Do NOT try to fix this with $wgUsePathInfo = true. It was tried and does nothing: getPathInfo()
# parses REQUEST_URI, not $_SERVER['PATH_INFO'], so the correctly-populated PATH_INFO ("/Forside")
# is never consulted. $wgUsePathInfo only controls *whether* the REQUEST_URI parse is attempted.
#
# Query-style URLs carry the title in the query string, which the prefix strip leaves untouched.
# Literal "/wiki/index.php" rather than "$wgScript" — $wgScript is not populated until Setup.php
# runs, i.e. after this file is parsed, so interpolating it here yields an empty string.
#
# The alternative is removing Coolify's stripprefix middleware so $wgScriptPath matches natively;
# that means overriding Coolify's generated Traefik labels, which is more fragile than accepting
# query-style URLs. Moving the wiki to wiki.gahk.dk would remove the problem entirely.
$wgArticlePath = "/wiki/index.php?title=$1";

## The protocol and server name to use in fully-qualified URLs
$wgServer = gahkEnv('MW_SERVER', 'https://gahk.dk');

## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";

$wgLogo = "$wgScriptPath/resources/assets/logo.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "it@gahk.dk";
$wgPasswordSender = "it@gahk.dk";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = gahkEnv('MW_DB_HOST');
$wgDBname = gahkEnv('MW_DB_NAME', 'gahk_wiki');
$wgDBuser = gahkEnv('MW_DB_USER', 'wiki');
$wgDBpassword = gahkEnv('MW_DB_PASSWORD');

# MySQL specific settings — the imported wiki.sql keeps the legacy `wiki` table prefix.
$wgDBprefix = "wiki";

# Table options for installation/update. InnoDB: the source database was converted from MyISAM
# before the 2026-08-04 dump, so every imported table is already InnoDB.
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons = false;

$wgShellLocale = "en_US.utf8";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "da";

# Rotate these at deploy time; the legacy values are considered compromised (scope §5).
$wgSecretKey = gahkEnv('MW_SECRET_KEY');
$wgUpgradeKey = gahkEnv('MW_UPGRADE_KEY');

## Default skin
$wgDefaultSkin = "vector";

$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

# The following permissions were set based on your choice in the installer.
# NOTE: read=false means the wiki is fully private — anonymous users cannot read any page. Combined
# with GahkAuthLogin being the only primaryauth provider and strict()===true, an unreachable Postgres
# locks everyone out, sysops included. See CUTOVER.md Phase 5A for the break-glass procedure.
$wgGroupPermissions['*']['read'] = false;
$wgGroupPermissions['*']['edit'] = false;


# End of automatically generated settings.
# Add more configuration options below.

$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['autocreateaccount'] = true;
$wgGroupPermissions['sysop']['createaccount'] = true;

// Use GAHK alumneliste

$wgEnableUploads = true;
$wgFileExtensions[] = 'doc';
$wgFileExtensions[] = 'docx';
$wgFileExtensions[] = 'xls';
$wgFileExtensions[] = 'xlsx';
$wgFileExtensions[] = 'odt';
$wgFileExtensions[] = 'ods';
$wgFileExtensions[] = 'pdf';

# Deliberately BELOW the Dockerfile's upload_max_filesize (72M), not equal to it. MediaWiki checks
# the size only after PHP has accepted the file, so anything PHP rejects never reaches this check —
# and PHP rejects silently, leaving "the file you uploaded seems to be empty" as the only clue. With
# a margin, MediaWiki is always the one that answers, and it says what the limit actually is.
#
# Without this line MediaWiki's default is 100M, i.e. *above* PHP's ceiling, which is the wrong way
# round: every upload between the two limits would fail with the unhelpful message instead of the
# helpful one.
$wgMaxUploadSize = 64 * 1024 * 1024;


wfLoadExtension('ShowRealUsernames');
wfLoadExtension('RealNames');
wfLoadExtension('GahkAuthLogin');

wfLoadSkin('Vector');
wfLoadSkin('MonoBook');
wfLoadSkin('Modern');
wfLoadSkin('CologneBlue');

$wgAuthManagerAutoConfig = [
    'preauth'       => [
        MediaWiki\Auth\ThrottlePreAuthenticationProvider::class => [
            'class' => MediaWiki\Auth\ThrottlePreAuthenticationProvider::class,
            'sort'  => 0,
        ],
    ],
    'primaryauth'   => [
        // Comment this entry out and reload to fall back to local MediaWiki passwords — the
        // break-glass path when Postgres is unreachable. See CUTOVER.md Phase 5A.
        'gahk' => [
            'class' => Gahk\GahkAuthLogin::class,
            'sort'  => 0,
        ],
    ],
    'secondaryauth' => [
        MediaWiki\Auth\CheckBlocksSecondaryAuthenticationProvider::class       => [
            'class' => MediaWiki\Auth\CheckBlocksSecondaryAuthenticationProvider::class,
            'sort'  => 50,
        ],
        MediaWiki\Auth\ResetPasswordSecondaryAuthenticationProvider::class     => [
            'class' => MediaWiki\Auth\ResetPasswordSecondaryAuthenticationProvider::class,
            'sort'  => 100,
        ],
        MediaWiki\Auth\EmailNotificationSecondaryAuthenticationProvider::class => [
            'class' => MediaWiki\Auth\EmailNotificationSecondaryAuthenticationProvider::class,
            'sort'  => 200,
        ],
        \Gahk\GahkAuthChangeName::class                                        => [
            'class' => \Gahk\GahkAuthChangeName::class,
            'sort'  => 0,
        ],
    ],
];

$wgShowExceptionDetails = false;
