# Generated by Django 5.2.17 on 2026-09-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("den_hurtige", "0006_remove_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quickcomment",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
