# Generated by Django 5.2.17 on 2026-09-16 18:57

from django.conf import settings
from django.db import migrations, models

import den_hurtige.models


class Migration(migrations.Migration):
    dependencies = [
        ("den_hurtige", "0007_alter_quickcomment_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="quickpost",
            name="expires_at",
            field=models.DateTimeField(
                default=den_hurtige.models.get_default_expiration,
                help_text="Hvornår beskeden forlader feedet og lægges i arkivet.",
            ),
        ),
        migrations.AddIndex(
            model_name="quickpost",
            index=models.Index(fields=["channel", "-created_at"], name="dh_archive_page_idx"),
        ),
    ]
