# Generated by Django 5.2.17 on 2026-09-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("den_hurtige", "0008_alter_quickpost_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickpost",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Sat hvis beskeden er slettet. Selve teksten og billedet er så væk for altid.",
                null=True,
            ),
        ),
    ]
