# Generated by Django 5.2.17 on 2026-10-07 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KitchenMonthlyState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="KitchenShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("morning", "Morgenvagt"),
                            ("midday", "Middagsvagt"),
                            ("evening", "Aftensvagt"),
                            ("special", "Særlig vagt"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("spots", models.PositiveSmallIntegerField(default=1)),
                ("points_per_spot", models.PositiveSmallIntegerField()),
                ("bonus_points", models.PositiveSmallIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_disabled", models.BooleanField(default=False)),
                ("disabled_reason", models.CharField(blank=True, max_length=255)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="KitchenPointEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("shift", "Vagt"),
                            ("monthly", "Månedlig afregning"),
                            ("absence", "Udeblivelse"),
                            ("trade", "Vagtbytte"),
                            ("manual", "Manuel postering"),
                        ],
                        max_length=10,
                    ),
                ),
                ("balance_before", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("message", models.CharField(max_length=255)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="kitchen.kitchenshift",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="KitchenAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spots", models.PositiveSmallIntegerField(default=1)),
                ("for_sale", models.BooleanField(default=False)),
                ("sale_bonus", models.PositiveSmallIntegerField(default=0)),
                ("put_for_sale_at", models.DateTimeField(blank=True, null=True)),
                ("awarded_points", models.IntegerField(default=0)),
                ("is_absent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="kitchen.kitchenshift",
                    ),
                ),
            ],
            options={
                "ordering": ["shift__starts_at", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="kitchenshift",
            index=models.Index(fields=["starts_at"], name="kitchen_kit_starts__0e177d_idx"),
        ),
        migrations.AddIndex(
            model_name="kitchenshift",
            index=models.Index(
                fields=["ends_at", "completed_at"],
                name="kitchen_kit_ends_at_fdcc6b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="kitchenshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "special"), _negated=True),
                fields=("date", "kind"),
                name="uniq_kitchen_standard_shift",
            ),
        ),
        migrations.AddIndex(
            model_name="kitchenpointentry",
            index=models.Index(fields=["resident", "-id"], name="kitchen_kit_residen_57997f_idx"),
        ),
        migrations.AddConstraint(
            model_name="kitchenpointentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "monthly")),
                fields=("resident", "year", "month"),
                name="uniq_kitchen_monthly_per_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="kitchenassignment",
            constraint=models.UniqueConstraint(fields=("shift", "resident"), name="uniq_kitchen_assignment"),
        ),
    ]
