# Generated by Django 5.2.17 on 2026-10-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchenassignment",
            name="self_enrolled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
