# Generated by Django 5.2.17 on 2026-09-21 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

# Seed values from the design doc's "arithmetic" section: morgen/frokost are 1h/1person on both
# weekday and weekend; only aftenvagt differs (3h/2 people on a weekday, 2h/1 person at a weekend).
# (kind, weekend, duration_minutes, headcount)
_VAGTREGLER = [
    ("morgen", False, 60, 1),
    ("morgen", True, 60, 1),
    ("frokost", False, 60, 1),
    ("frokost", True, 60, 1),
    ("aften", False, 180, 2),
    ("aften", True, 120, 1),
]


def seed_vagtregler(apps, schema_editor) -> None:  # noqa: ANN001
    """Create the 6 (kind x weekday/weekend) shift rules. Køkkengruppen edits them via the admin."""
    vagt_regel = apps.get_model("koekken", "VagtRegel")
    for kind, weekend, duration_minutes, headcount in _VAGTREGLER:
        vagt_regel.objects.get_or_create(
            kind=kind,
            weekend=weekend,
            defaults={"duration_minutes": duration_minutes, "headcount": headcount},
        )


def noop(apps, schema_editor) -> None:  # noqa: ANN001
    pass


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Periode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("efteraar", "Efterår"), ("foraar", "Forår"), ("sommer", "Sommer")],
                        max_length=10,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "ordering": ["year", "start_date"],
                "constraints": [
                    models.UniqueConstraint(fields=("kind", "year"), name="uniq_periode_kind_year")
                ],
            },
        ),
        migrations.CreateModel(
            name="Vagt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("morgen", "Morgenvagt"),
                            ("frokost", "Frokostvagt"),
                            ("aften", "Aftenvagt"),
                        ],
                        max_length=10,
                    ),
                ),
                ("headcount", models.PositiveSmallIntegerField()),
                ("duration_minutes", models.PositiveSmallIntegerField()),
                (
                    "periode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vagter",
                        to="koekken.periode",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "kind"],
            },
        ),
        migrations.CreateModel(
            name="KoekkenPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("delta_minutes", models.IntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("forpligtelse", "Forpligtelse"),
                            ("arbejde", "Udført arbejde"),
                            ("justering", "Manuel justering"),
                            ("startsaldo", "Startsaldo"),
                            ("tilbagefoersel", "Tilbageførsel"),
                        ],
                        max_length=15,
                    ),
                ),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="koekken_posts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="koekken_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "periode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="koekken_posts",
                        to="koekken.periode",
                    ),
                ),
                (
                    "vagt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="koekken_posts",
                        to="koekken.vagt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VagtRegel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("morgen", "Morgenvagt"),
                            ("frokost", "Frokostvagt"),
                            ("aften", "Aftenvagt"),
                        ],
                        max_length=10,
                    ),
                ),
                ("weekend", models.BooleanField(help_text="Gælder for lørdag/søndag frem for hverdage.")),
                ("duration_minutes", models.PositiveSmallIntegerField()),
                ("headcount", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["kind", "weekend"],
                "constraints": [
                    models.UniqueConstraint(fields=("kind", "weekend"), name="uniq_vagtregel_kind_weekend")
                ],
            },
        ),
        migrations.CreateModel(
            name="VagtTildeling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("tildelt", "Tildelt"),
                            ("udfoert", "Udført"),
                            ("anmeldt", "Anmeldt"),
                            ("ikke_udfoert", "Ikke udført"),
                        ],
                        default="tildelt",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="koekken_tildelinger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vagt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tildelinger",
                        to="koekken.vagt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Praeference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday_unavailable",
                    models.BooleanField(
                        default=False,
                        help_text="Ruter beboeren til weekend-puljen for morgen-/frokostvagt (tier A) i denne periode.",
                    ),
                ),
                (
                    "periode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="praeferencer",
                        to="koekken.periode",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="koekken_praeferencer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resident", "periode"), name="uniq_praeference_resident_periode"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="vagt",
            index=models.Index(fields=["date"], name="koekken_vag_date_7dc9c2_idx"),
        ),
        migrations.AddConstraint(
            model_name="vagt",
            constraint=models.UniqueConstraint(fields=("date", "kind"), name="uniq_vagt_date_kind"),
        ),
        migrations.AddIndex(
            model_name="koekkenpost",
            index=models.Index(fields=["resident", "created_at"], name="koekken_koe_residen_99488a_idx"),
        ),
        migrations.AddConstraint(
            model_name="koekkenpost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "forpligtelse")),
                fields=("resident", "periode", "month"),
                name="uniq_koekken_forpligtelse_per_period_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="vagttildeling",
            constraint=models.UniqueConstraint(
                fields=("vagt", "resident"), name="uniq_vagttildeling_vagt_resident"
            ),
        ),
        migrations.RunPython(seed_vagtregler, noop),
    ]
