# Generated by Django 5.2.17 on 2026-09-22 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("koekken", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="koekkenpost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "startsaldo")),
                fields=("resident",),
                name="uniq_koekken_startsaldo_per_resident",
            ),
        ),
    ]
