# Generated by Django 5.2.17 on 2026-09-22 05:26

from django.db import migrations, models

import koekken.models


class Migration(migrations.Migration):
    dependencies = [
        ("koekken", "0002_koekkenpost_uniq_koekken_startsaldo_per_resident"),
    ]

    operations = [
        migrations.AddField(
            model_name="praeference",
            name="declared_at",
            field=models.DateField(
                default=koekken.models._declared_at_default,
                help_text="Hvornår denne præference (senest) blev erklæret -- bruges som FCFS-tiebreak ved allokering (Amendment 1, A1.1).",
            ),
        ),
    ]
