# Generated by Django 5.2.17 on 2026-09-28 14:27

import datetime

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

# Seed values from the P2 design doc's "The marking window" table: same start time for a kind's
# weekday and weekend VagtRegel row.
_START_TIMES = {
    "morgen": datetime.time(6, 0),
    "frokost": datetime.time(12, 0),
    "aften": datetime.time(17, 0),
}


def seed_start_times(apps, schema_editor) -> None:  # noqa: ANN001
    vagt_regel = apps.get_model("koekken", "VagtRegel")
    for kind, start_time in _START_TIMES.items():
        vagt_regel.objects.filter(kind=kind).update(start_time=start_time)


def noop(apps, schema_editor) -> None:  # noqa: ANN001
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("koekken", "0003_praeference_declared_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vagtregel",
            name="start_time",
            field=models.TimeField(
                default=datetime.time(6, 0),
                help_text="Hvornår vagten kan markeres udført fra køkken-tabletten (læses direkte herfra, aldrig snapshottet på Vagt -- se modellens docstring).",
            ),
        ),
        migrations.RunPython(seed_start_times, noop),
        migrations.CreateModel(
            name="PraeferenceDag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("morgen", "Morgenvagt"),
                            ("frokost", "Frokostvagt"),
                            ("aften", "Aftenvagt"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        help_text="0 = mandag .. 6 = søndag (Python's date.weekday()).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "praeference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dage",
                        to="koekken.praeference",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "weekday"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("praeference", "kind", "weekday"),
                        name="uniq_praeferencedag_praeference_kind_weekday",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VagtAnmeldelse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("tildelt", "Tildelt"),
                            ("udfoert", "Udført"),
                            ("anmeldt", "Anmeldt"),
                            ("ikke_udfoert", "Ikke udført"),
                        ],
                        max_length=15,
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Begrundelse")),
                (
                    "status",
                    models.CharField(
                        choices=[("aaben", "Åben"), ("opretholdt", "Opretholdt"), ("afvist", "Afvist")],
                        default="aaben",
                        max_length=10,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "flagged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="koekken_anmeldelser_lavet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="koekken_anmeldelser_afgjort",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vagt_tildeling",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anmeldelser",
                        to="koekken.vagttildeling",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "aaben")),
                        fields=("vagt_tildeling",),
                        name="uniq_vagtanmeldelse_open_per_tildeling",
                    )
                ],
            },
        ),
    ]
