# Generated by Django 5.2.17 on 2026-10-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("koekken", "0004_vagtregel_start_time_praeferencedag_vagtanmeldelse"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fridag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("morgen", "Morgenvagt"),
                            ("frokost", "Frokostvagt"),
                            ("aften", "Aftenvagt"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, verbose_name="Begrundelse")),
            ],
            options={
                "ordering": ["date", "kind"],
                "constraints": [
                    models.UniqueConstraint(fields=("date", "kind"), name="uniq_fridag_date_kind")
                ],
            },
        ),
    ]
