# Generated by Django 5.2.17 on 2026-10-04 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("koekken", "0005_fridag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VagtBytte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aaben", "Åben"),
                            ("overtaget", "Overtaget"),
                            ("overtaget_hel", "Hele vagten overtaget"),
                            ("byttet", "Byttet"),
                            ("trukket", "Trukket tilbage"),
                            ("bortfaldet", "Bortfaldet"),
                        ],
                        default="aaben",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "overtaget_af",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="koekken_overtagelser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tilbudt_af",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="koekken_byttetilbud",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tildeling",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="byttetilbud",
                        to="koekken.vagttildeling",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "aaben")),
                        fields=("tildeling",),
                        name="uniq_vagtbytte_open_per_tildeling",
                    )
                ],
            },
        ),
    ]
