# Generated by Django 5.2.17 on 2026-10-05 09:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("koekken", "0006_vagtbytte"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VagtBytteForslag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aaben", "Åben"),
                            ("accepteret", "Accepteret"),
                            ("afvist", "Afvist"),
                            ("trukket", "Trukket tilbage"),
                            ("bortfaldet", "Bortfaldet"),
                        ],
                        default="aaben",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bytte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forslag",
                        to="koekken.vagtbytte",
                    ),
                ),
                (
                    "foreslaaet_af",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="koekken_bytteforslag",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modydelse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="byttemodydelser",
                        to="koekken.vagttildeling",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "aaben")),
                        fields=("bytte", "modydelse"),
                        name="uniq_vagtbytteforslag_open_per_bytte_modydelse",
                    )
                ],
            },
        ),
    ]
