# Generated by Django 5.2.17 on 2026-10-05 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("den_hurtige", "0009_quickpost_deleted_at"),
        ("koekken", "0007_vagtbytteforslag"),
    ]

    operations = [
        migrations.AddField(
            model_name="vagtbytte",
            name="hurtig_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="den_hurtige.quickpost",
            ),
        ),
    ]
