# Generated by Django 5.2.17 on 2026-10-06 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("koekken", "0008_vagtbytte_hurtig_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fravaer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="koekken_fravaer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
                "indexes": [
                    models.Index(fields=["resident", "start_date"], name="koekken_fra_residen_d4ce6a_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_date__lte", models.F("end_date"))),
                        name="fravaer_start_lte_end",
                    )
                ],
            },
        ),
    ]
