# Generated by Django 5.2.17 on 2026-10-07 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("koekken", "0009_fravaer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="koekkenpost",
            name="kind",
            field=models.CharField(
                choices=[
                    ("forpligtelse", "Forpligtelse"),
                    ("arbejde", "Udført arbejde"),
                    ("justering", "Manuel justering"),
                    ("startsaldo", "Startsaldo"),
                    ("tilbagefoersel", "Tilbageførsel"),
                    ("festkredit", "Festkredit"),
                    ("festbidrag", "Festbidrag"),
                ],
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="FestKredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("navn", models.CharField(max_length=100, verbose_name="Begivenhed")),
                ("dato", models.DateField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("fortrudt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="koekken_festkreditter_oprettet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fortrudt_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="koekken_festkreditter_fortrudt",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "festkredit",
                "verbose_name_plural": "festkreditter",
                "ordering": ["-dato", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="koekkenpost",
            name="festkredit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="poster",
                to="koekken.festkredit",
            ),
        ),
    ]
