# Generated by Django 5.2.17 on 2026-08-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_pushsubscription_wants_begivenheder"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushsubscription",
            name="wants_reparationer",
            field=models.BooleanField(default=False, verbose_name="Reparationer"),
        ),
    ]
