# Generated by Django 5.2.17 on 2026-09-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_fotogruppen_workgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushsubscription",
            name="wants_koekken",
            field=models.BooleanField(default=False, verbose_name="Køkkenvagter"),
        ),
    ]
