# Generated by Django 5.2.17 on 2026-10-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_fotogruppen_workgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushsubscription",
            name="wants_koekkenvagter",
            field=models.BooleanField(default=False, verbose_name="Køkkenvagter"),
        ),
    ]
