# Generated by Django 5.2.17 on 2026-09-19 13:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[("docx", "Word-dokument"), ("xlsx", "Regneark"), ("pptx", "Præsentation")],
                        max_length=12,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("extension", models.CharField(max_length=12)),
                ("object_key", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentEditingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("document_key", models.CharField(max_length=128, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Aktiv"), ("finished", "Afsluttet"), ("failed", "Fejlet")],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("final_saved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editing_sessions",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("object_key", models.CharField(max_length=500, unique=True)),
                ("content_sha256", models.CharField(max_length=64)),
                ("size", models.PositiveBigIntegerField()),
                (
                    "save_type",
                    models.CharField(
                        choices=[
                            ("initial", "Oprettet"),
                            ("force_save", "Løbende gemning"),
                            ("final", "Endelig gemning"),
                            ("restore", "Gendannet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
                (
                    "editing_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="documents.documenteditingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-sequence"],
            },
        ),
        migrations.AddField(
            model_name="documenteditingsession",
            name="source_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_sessions",
                to="documents.documentversion",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="documents.documentversion",
            ),
        ),
        migrations.CreateModel(
            name="DocumentCallbackReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("payload_sha256", models.CharField(max_length=64)),
                ("status", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="callback_receipts",
                        to="documents.documenteditingsession",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "payload_sha256"), name="unique_document_callback_receipt"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "permission",
                    models.CharField(choices=[("editor", "Redaktør"), ("viewer", "Læser")], max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="documents.document",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("document", "resident"), name="unique_document_grant")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "sequence"), name="unique_document_version_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="documenteditingsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("document",),
                name="one_active_document_session",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["owner", "deleted_at", "-updated_at"], name="documents_d_owner_i_b08de7_idx"
            ),
        ),
    ]
