# Generated by Django 5.2.17 on 2026-09-06 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0007_pushsubscription_wants_reparationer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Navn")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "effective_workgroup",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.workgroup",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="arkiv.archivefolder",
                    ),
                ),
                (
                    "workgroup",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tom = synlig for alle beboere. Sat = kun for gruppens nuvaerende medlemmer.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archive_folders",
                        to="core.workgroup",
                        verbose_name="Embedsgruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mappe",
                "verbose_name_plural": "Mapper",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArchiveFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Filnavn")),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("size", models.PositiveBigIntegerField()),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("has_thumbnail", models.BooleanField(default=False)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="arkiv.archivefolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fil",
                "verbose_name_plural": "Filer",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="archivefolder",
            index=models.Index(fields=["parent", "name"], name="folder_parent_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="archivefolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("parent", "name"),
                name="uniq_folder_name_per_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="archivefile",
            index=models.Index(fields=["folder", "name"], name="file_folder_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="archivefile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("folder", "name"),
                name="uniq_file_name_per_folder",
            ),
        ),
    ]
