# Generated by Django 5.2.17 on 2026-09-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arkiv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivefile",
            name="has_preview",
            field=models.BooleanField(default=False),
        ),
    ]
