# Generated by Django 5.2.17 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arkiv", "0002_archivefile_has_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivefolder",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="archivefolder",
            name="unlocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]